name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish the container image
    uses: docker/login-action@v2
    with:
      registry: ghcr.io
      username: ${{ secrets.GHCR_USER }}
      password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      run: |
        docker build . --file Dockerfile --tag dotdev:latest --tag dotdev:${{ github.sha }}
        docker push ghcr.io/tmlamb/dotdev:latest
  
